# Generated by Django 4.2.7 on 2024-01-13 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('check_verification', 'Can check email verification of account')]},
        ),
    ]
