# Generated by Django 4.2.7 on 2024-01-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_last_change',
            field=models.DateTimeField(auto_now=True, verbose_name='дата изменения'),
        ),
    ]
